version: '3'
services:
  projects-service:
    build:
      context: ./projects-service
      dockerfile: Dockerfile
    volumes:
      - ./projects-service:/projects-service
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    networks:
      - flowiseNetwork

  employees-service:
    build:
      context: ./employees-service
      dockerfile: Dockerfile
    volumes:
      - ./employees-service:/employees-service
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
    networks:
      - flowiseNetwork

  vehicles-service:
    build:
      context: ./vehicles-service
      dockerfile: Dockerfile
    volumes:
      - ./vehicles-service:/vehicles-service
    ports:
      - "3002:3000"
    environment:
      - RAILS_ENV=development
    networks:
      - flowiseNetwork

  bdo-service:
    build:
      context: ./bdo-service
      dockerfile: Dockerfile
    volumes:
      - ./bdo-service:/bdo-service
    ports:
      - "3003:3000"
    environment:
      - RAILS_ENV=development
    networks:
      - flowiseNetwork

networks:
  flowiseNetwork: