---
openapi: 3.0.1
info:
  title: API Projects
  version: v1
paths:
  "/api/projects/{project_id}/comments":
    parameters:
    - name: project_id
      in: path
      description: project_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      tags:
      - Comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
  "/api/projects/{project_id}/comments/{id}":
    parameters:
    - name: project_id
      in: path
      description: project_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
    put:
      summary: update comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
    delete:
      summary: delete comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
  "/api/projects/employee_assignments":
    get:
      summary: show employee_assignment
      tags:
      - Employee assigments
      responses:
        '200':
          description: successful
    post:
      summary: create employee_assignment
      tags:
      - Employee assigments
      responses:
        '200':
          description: successful
    delete:
      summary: delete employee_assignment
      tags:
      - Employee assigments
      responses:
        '200':
          description: successful
  "/api/projects":
    get:
      summary: list projects
      tags:
      - Projects
      responses:
        '200':
          description: successful
    post:
      summary: create project
      tags:
      - Projects
      responses:
        '200':
          description: successful
  "/api/projects/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show project
      tags:
      - Projects
      responses:
        '200':
          description: successful
    delete:
      summary: delete project
      tags:
      - Projects
      responses:
        '200':
          description: successful
    put:
      summary: update project
      tags:
      - Projects
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
